/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simoncherry_artest_util_JNIUtils */

#ifndef _Included_com_simoncherry_artest_util_JNIUtils
#define _Included_com_simoncherry_artest_util_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simoncherry_artest_util_JNIUtils
 * Method:    doGrayScale
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_artest_util_JNIUtils_doGrayScale
        (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_artest_util_JNIUtils
 * Method:    doFaceSwap
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simoncherry_artest_util_JNIUtils_doFaceSwap
        (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif